# Generated by Django 6.1.1 on 2026-10-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('students', models.PositiveIntegerField(default=0)),
                ('room', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
